[package]
name = "input"
version = "0.1.0"
edition = "2021"
description = "Input abstraction for the insiculous_2d game engine"

[dependencies]
log = { workspace = true }
winit = { workspace = true }
thiserror = { workspace = true }