[package]
name = "builtin_states"
version = "0.1.0"
edition = "2024"

[dependencies]
engine_core = { path = "../engine_core"}
renderer = { path = "../renderer"}
input = { path = "../input"}
winit = { workspace = true }
once_cell = { workspace = true }